os_version:
  linux_64: cos7
  linux_aarch64: cos7
  linux_ppc64le: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_aarch64: default
